/**
@file	pnlLDO.h
@author Lime Microsystems
*/

#ifndef pnlLDO_H
#define pnlLDO_H
//(*Headers(pnlLDO)
#include <wx/panel.h>
class wxCheckBox;
class wxNotebookEvent;
class wxComboBox;
class wxNotebook;
class wxStaticText;
class wxFlexGridSizer;
class wxStaticBoxSizer;
//*)
#include <map>
#include "RegistersMap.h"
#include "GUIPanel.h"
class LMS7002_MainControl;
class ComboBoxMap;
class pnlLDO : public wxPanel, GUIPanel
{
public:
    pnlLDO(wxWindow* parent,wxWindowID id=wxID_ANY,const wxPoint& pos=wxDefaultPosition,const wxSize& size=wxDefaultSize, int style=0, wxString name="");
    void Initialize(LMS7002_MainControl *pControl);
    void UpdateGUI();
    virtual ~pnlLDO();

//(*Declarations(pnlLDO)
wxCheckBox* chkEN_LDO_DIGSXR;
ComboBoxMap* cmbRDIV_DIGIp2;
wxCheckBox* chkSPDUP_LDO_AFE;
wxCheckBox* chkEN_G_LDOP;
wxCheckBox* chkSPDUP_LDO_DIVGN;
ComboBoxMap* cmbRDIV_DIVSXT;
wxCheckBox* chkBYP_LDO_TXBUF;
wxCheckBox* chkSPDUP_LDO_DIGIp2;
wxCheckBox* chkPD_LDO_DIGIp1;
wxCheckBox* chkSPDUP_LDO_DIGIp1;
wxCheckBox* chkPD_LDO_SPIBUF;
wxCheckBox* chkEN_LOADIMP_LDO_MXRFE;
ComboBoxMap* cmbRDIV_VCOSXT;
wxCheckBox* chkEN_LOADIMP_LDO_DIG;
wxCheckBox* chkBYP_LDO_TIA12;
wxCheckBox* chkEN_LOADIMP_LDO_LNA14;
wxCheckBox* chkEN_LDO_DIVGN;
ComboBoxMap* cmbRDIV_TPAD;
wxPanel* Panel2;
wxCheckBox* chkEN_LDO_DIGSXT;
wxCheckBox* chkEN_LOADIMP_LDO_TXBUF;
wxCheckBox* chkBYP_LDO_DIG;
wxCheckBox* chkBYP_LDO_RBB;
wxCheckBox* chkBYP_LDO_LNA14;
wxCheckBox* chkBYP_LDO_CPSXT;
wxStaticText* StaticText27;
ComboBoxMap* cmbRDIV_AFE;
wxCheckBox* chkEN_LDO_TPAD;
wxCheckBox* chkPD_LDO_DIGIp2;
wxCheckBox* chkSPDUP_LDO_TBB;
wxCheckBox* chkBYP_LDO_CPSXR;
wxCheckBox* chkEN_LOADIMP_LDO_CPSXR;
wxCheckBox* chkBYP_LDO_AFE;
wxCheckBox* chkBYP_LDO_MXRFE;
wxCheckBox* chkSPDUP_LDO_TXBUF;
ComboBoxMap* cmbRDIV_TBB;
ComboBoxMap* cmbRDIV_DIVGN;
wxCheckBox* chkBYP_LDO_RXBUF;
ComboBoxMap* cmbRDIV_DIGIp1;
ComboBoxMap* cmbRDIV_MXRFE;
wxCheckBox* chkEN_LDO_TIA14;
wxCheckBox* chkSPDUP_LDO_DIVSXT;
ComboBoxMap* cmbRDIV_DIGSXT;
wxStaticText* StaticText5;
wxStaticText* StaticText25;
wxStaticText* StaticText6;
wxCheckBox* chkBYP_LDO_VCOSXR;
ComboBoxMap* cmbRDIV_VCOSXR;
wxCheckBox* chkEN_LOADIMP_LDO_CPGN;
wxNotebook* Notebook1;
wxCheckBox* chkSPDUP_LDO_TLOB;
wxCheckBox* chkEN_LOADIMP_LDO_VCOSXT;
wxStaticText* StaticText19;
wxCheckBox* chkEN_LDO_LNA12;
wxCheckBox* chkSPDUP_LDO_DIGGN;
wxCheckBox* chkEN_LOADIMP_LDO_TBB;
wxCheckBox* chkEN_LOADIMP_LDO_DIVSXR;
ComboBoxMap* cmbRDIV_DIVSXR;
wxCheckBox* chkSPDUP_LDO_DIVSXR;
wxCheckBox* chkBYP_LDO_DIVSXT;
wxCheckBox* chkSPDUP_LDO_DIG;
wxStaticBoxSizer* BypassSizer;
wxStaticText* StaticText10;
wxCheckBox* chkSPDUP_LDO_TIA12;
wxFlexGridSizer* FlexGridSizer4;
ComboBoxMap* cmbRDIV_RBB;
ComboBoxMap* cmbRDIV_LNA12;
wxCheckBox* chkBYP_LDO_DIVSXR;
wxCheckBox* chkSPDUP_LDO_TPAD;
wxCheckBox* chkEN_LOADIMP_LDO_LNA12;
ComboBoxMap* cmbRDIV_CPSXT;
wxStaticText* StaticText23;
wxStaticText* StaticText12;
wxCheckBox* chkEN_LDO_TIA12;
wxStaticText* StaticText22;
wxCheckBox* chkBYP_LDO_TLOB;
wxCheckBox* chkEN_LOADIMP_LDO_SPIBUF;
ComboBoxMap* cmbRDIV_TXBUF;
wxCheckBox* chkEN_LDO_TXBUF;
wxCheckBox* chkEN_LDO_TBB;
wxCheckBox* chkSPDUP_LDO_LNA12;
wxCheckBox* chkEN_LDO_CPGN;
ComboBoxMap* cmbRDIV_TIA12;
wxCheckBox* chkEN_LDO_CPSXT;
ComboBoxMap* cmbRDIV_TLOB;
wxCheckBox* chkEN_LOADIMP_LDO_RBB;
wxCheckBox* chkEN_LDO_VCOSXR;
wxCheckBox* chkSPDUP_LDO_RXBUF;
wxCheckBox* chkSPDUP_LDO_SPIBUF;
wxStaticText* StaticText7;
ComboBoxMap* cmbRDIV_CPSXR;
wxStaticText* StaticText16;
wxStaticText* StaticText0;
wxCheckBox* chkBYP_LDO_LNA12;
wxCheckBox* chkBYP_LDO_TIA14;
wxCheckBox* chkSPDUP_LDO_LNA14;
wxCheckBox* chkEN_LOADIMP_LDO_TIA14;
wxCheckBox* chkSPDUP_LDO_CPGN;
wxStaticText* StaticText24;
wxCheckBox* chkEN_LOADIMP_LDO_TIA12;
wxCheckBox* chkEN_LDO_TLOB;
wxCheckBox* chkEN_LDO_DIVSXR;
wxCheckBox* chkEN_LOADIMP_LDO_DIGIp2;
wxCheckBox* chkEN_LDO_RXBUF;
wxCheckBox* chkSPDUP_LDO_CPSXT;
wxStaticText* StaticText14;
wxCheckBox* chkEN_LOADIMP_LDO_TPAD;
wxCheckBox* chkEN_LDO_AFE;
wxCheckBox* chkBYP_LDO_SPIBUF;
wxPanel* Panel3;
wxStaticText* StaticText18;
wxCheckBox* chkBYP_LDO_TPAD;
ComboBoxMap* cmbRDIV_CPGN;
wxCheckBox* chkEN_LOADIMP_LDO_AFE;
wxStaticText* StaticText13;
wxCheckBox* chkSPDUP_LDO_MXRFE;
wxCheckBox* chkSPDUP_LDO_VCOGN;
wxCheckBox* chkBYP_LDO_DIGSXT;
wxCheckBox* chkEN_G_LDO;
wxStaticText* StaticText20;
wxCheckBox* chkBYP_LDO_VCOGN;
wxCheckBox* chkSPDUP_LDO_VCOSXT;
wxCheckBox* chkSPDUP_LDO_TIA14;
wxCheckBox* chkBYP_LDO_VCOSXT;
wxCheckBox* chkSPDUP_LDO_DIGSXT;
wxCheckBox* chkEN_LOADIMP_LDO_VCOSXR;
wxCheckBox* chkEN_LDO_RBB;
wxCheckBox* chkEN_LOADIMP_LDO_DIGSXR;
wxCheckBox* chkEN_LOADIMP_LDO_DIGGN;
wxCheckBox* chkBYP_LDO_DIGIp1;
wxStaticText* StaticText21;
wxStaticText* StaticText4;
ComboBoxMap* cmbRDIV_VCOGN;
wxCheckBox* chkBYP_LDO_DIGIp2;
wxCheckBox* chkBYP_LDO_TBB;
wxCheckBox* chkEN_LOADIMP_LDO_DIGSXT;
wxCheckBox* chkSPDUP_LDO_VCOSXR;
wxCheckBox* chkEN_LDO_DIG;
wxCheckBox* chkBYP_LDO_DIGGN;
wxCheckBox* chkSPDUP_LDO_CPSXR;
wxStaticText* StaticText26;
wxStaticText* StaticText15;
wxCheckBox* chkEN_LOADIMP_LDO_CPSXT;
wxStaticText* StaticText8;
wxCheckBox* chkBYP_LDO_CPGN;
wxCheckBox* chkEN_LOADIMP_LDO_DIVGN;
ComboBoxMap* cmbRDIV_LNA14;
wxCheckBox* chkEN_LDO_MXRFE;
ComboBoxMap* cmbRDIV_DIGSXR;
ComboBoxMap* cmbRDIV_SPIBUF;
wxCheckBox* chkSPDUP_LDO_RBB;
wxCheckBox* chkBYP_LDO_DIVGN;
wxCheckBox* chkEN_LDO_LNA14;
wxCheckBox* chkEN_LDO_VCOGN;
wxCheckBox* chkEN_LDO_DIVSXT;
ComboBoxMap* cmbRDIV_DIG;
wxCheckBox* chkEN_LOADIMP_LDO_RXBUF;
wxStaticText* StaticText1;
wxStaticText* StaticText2;
ComboBoxMap* cmbRDIV_RXBUF;
ComboBoxMap* cmbRDIV_TIA14;
wxCheckBox* chkSPDUP_LDO_DIGSXR;
wxStaticText* StaticText17;
wxStaticText* StaticText11;
wxCheckBox* chkEN_LDO_VCOSXT;
wxCheckBox* chkEN_LDO_CPSXR;
wxCheckBox* chkEN_LOADIMP_LDO_DIGIp1;
wxCheckBox* chkEN_LOADIMP_LDO_TLOB;
wxStaticText* StaticText9;
wxCheckBox* chkEN_LDO_DIGGN;
ComboBoxMap* cmbRDIV_DIGGN;
wxCheckBox* chkEN_LOADIMP_LDO_DIVSXT;
wxCheckBox* chkBYP_LDO_DIGSXR;
wxCheckBox* chkEN_LOADIMP_LDO_VCOGN;
wxStaticText* StaticText3;
//*)

protected:
//(*Identifiers(pnlLDO)
static const long ID_EN_G_LDOP;
static const long ID_EN_G_LDO;
static const long ID_EN_LDO_DIVGN;
static const long ID_EN_LDO_DIGGN;
static const long ID_EN_LDO_CPGN;
static const long ID_EN_LDO_VCOGN;
static const long ID_EN_LDO_MXRFE;
static const long ID_EN_LDO_LNA14;
static const long ID_EN_LDO_LNA12;
static const long ID_EN_LDO_TIA14;
static const long ID_EN_LDO_DIVSXT;
static const long ID_EN_LDO_DIGSXT;
static const long ID_EN_LDO_CPSXT;
static const long ID_EN_LDO_VCOSXT;
static const long ID_EN_LDO_DIVSXR;
static const long ID_EN_LDO_DIGSXR;
static const long ID_EN_LDO_CPSXR;
static const long ID_EN_LDO_VCOSXR;
static const long ID_PD_LDO_DIGIp1;
static const long ID_PD_LDO_DIGIp2;
static const long ID_EN_LDO_TXBUF;
static const long ID_EN_LDO_RXBUF;
static const long ID_EN_LDO_AFE;
static const long ID_PD_LDO_SPIBUF;
static const long ID_EN_LDO_TBB;
static const long ID_EN_LDO_RBB;
static const long ID_EN_LDO_TIA12;
static const long ID_EN_LDO_TPAD;
static const long ID_EN_LDO_TLOB;
static const long ID_EN_LDO_DIG;
static const long ID_BYP_LDO_TBB;
static const long ID_BYP_LDO_TIA12;
static const long ID_BYP_LDO_TIA14;
static const long ID_BYP_LDO_TLOB;
static const long ID_BYP_LDO_TPAD;
static const long ID_BYP_LDO_TXBUF;
static const long ID_BYP_LDO_VCOGN;
static const long ID_BYP_LDO_VCOSXR;
static const long ID_BYP_LDO_VCOSXT;
static const long ID_BYP_LDO_AFE;
static const long ID_BYP_LDO_CPGN;
static const long ID_BYP_LDO_CPSXR;
static const long ID_BYP_LDO_CPSXT;
static const long ID_BYP_LDO_DIG;
static const long ID_BYP_LDO_DIGGN;
static const long ID_BYP_LDO_DIGSXR;
static const long ID_BYP_LDO_DIGSXT;
static const long ID_BYP_LDO_DIVGN;
static const long ID_BYP_LDO_DIVSXR;
static const long ID_BYP_LDO_DIVSXT;
static const long ID_BYP_LDO_LNA12;
static const long ID_BYP_LDO_LNA14;
static const long ID_BYP_LDO_MXRFE;
static const long ID_BYP_LDO_RBB;
static const long ID_BYP_LDO_RXBUF;
static const long ID_BYP_LDO_SPIBUF;
static const long ID_BYP_LDO_DIGIp2;
static const long ID_BYP_LDO_DIGIp1;
static const long ID_SPDUP_LDO_TBB;
static const long ID_SPDUP_LDO_TIA12;
static const long ID_SPDUP_LDO_TIA14;
static const long ID_SPDUP_LDO_TLOB;
static const long ID_SPDUP_LDO_TPAD;
static const long ID_SPDUP_LDO_TXBUF;
static const long ID_SPDUP_LDO_VCOGN;
static const long ID_SPDUP_LDO_DIVSXR;
static const long ID_SPDUP_LDO_DIVSXT;
static const long ID_SPDUP_LDO_AFE;
static const long ID_SPDUP_LDO_CPGN;
static const long ID_SPDUP_LDO_VCOSXR;
static const long ID_SPDUP_LDO_VCOSXT;
static const long ID_SPDUP_LDO_DIG;
static const long ID_SPDUP_LDO_DIGGN;
static const long ID_SPDUP_LDO_DIGSXR;
static const long ID_SPDUP_LDO_DIGSXT;
static const long ID_SPDUP_LDO_DIVGN;
static const long ID_SPDUP_LDO_CPSXR;
static const long ID_SPDUP_LDO_CPSXT;
static const long ID_SPDUP_LDO_LNA12;
static const long ID_SPDUP_LDO_LNA14;
static const long ID_SPDUP_LDO_MXRFE;
static const long ID_SPDUP_LDO_RBB;
static const long ID_SPDUP_LDO_RXBUF;
static const long ID_SPDUP_LDO_SPIBUF;
static const long ID_SPDUP_LDO_DIGIp2;
static const long ID_SPDUP_LDO_DIGIp1;
static const long ID_EN_LOADIMP_LDO_TBB;
static const long ID_EN_LOADIMP_LDO_TIA12;
static const long ID_EN_LOADIMP_LDO_TIA14;
static const long ID_EN_LOADIMP_LDO_TLOB;
static const long ID_EN_LOADIMP_LDO_TPAD;
static const long ID_EN_LOADIMP_LDO_TXBUF;
static const long ID_EN_LOADIMP_LDO_VCOGN;
static const long ID_EN_LOADIMP_LDO_VCOSXR;
static const long ID_EN_LOADIMP_LDO_VCOSXT;
static const long ID_EN_LOADIMP_LDO_AFE;
static const long ID_EN_LOADIMP_LDO_CPGN;
static const long ID_EN_LOADIMP_LDO_DIVSXR;
static const long ID_EN_LOADIMP_LDO_DIVSXT;
static const long ID_EN_LOADIMP_LDO_DIG;
static const long ID_EN_LOADIMP_LDO_DIGGN;
static const long ID_EN_LOADIMP_LDO_DIGSXR;
static const long ID_EN_LOADIMP_LDO_DIGSXT;
static const long ID_EN_LOADIMP_LDO_DIVGN;
static const long ID_EN_LOADIMP_LDO_CPSXR;
static const long ID_EN_LOADIMP_LDO_CPSXT;
static const long ID_EN_LOADIMP_LDO_LNA12;
static const long ID_EN_LOADIMP_LDO_LNA14;
static const long ID_EN_LOADIMP_LDO_MXRFE;
static const long ID_EN_LOADIMP_LDO_RBB;
static const long ID_EN_LOADIMP_LDO_RXBUF;
static const long ID_EN_LOADIMP_LDO_SPIBUF;
static const long ID_EN_LOADIMP_LDO_DIGIp2;
static const long ID_EN_LOADIMP_LDO_DIGIp1;
static const long ID_PANEL3;
static const long ID_STATICTEXT1;
static const long ID_RDIV_VCOSXR;
static const long ID_STATICTEXT2;
static const long ID_RDIV_VCOSXT;
static const long ID_STATICTEXT3;
static const long ID_RDIV_TXBUF;
static const long ID_STATICTEXT4;
static const long ID_RDIV_VCOGN;
static const long ID_STATICTEXT5;
static const long ID_RDIV_TLOB;
static const long ID_STATICTEXT6;
static const long ID_RDIV_TPAD;
static const long ID_STATICTEXT7;
static const long ID_RDIV_TIA12;
static const long ID_STATICTEXT8;
static const long ID_RDIV_TIA14;
static const long ID_STATICTEXT9;
static const long ID_RDIV_RXBUF;
static const long ID_STATICTEXT10;
static const long ID_RDIV_TBB;
static const long ID_STATICTEXT11;
static const long ID_RDIV_MXRFE;
static const long ID_STATICTEXT12;
static const long ID_RDIV_RBB;
static const long ID_STATICTEXT13;
static const long ID_RDIV_LNA12;
static const long ID_STATICTEXT14;
static const long ID_RDIV_LNA14;
static const long ID_STATICTEXT15;
static const long ID_RDIV_DIVSXR;
static const long ID_STATICTEXT16;
static const long ID_RDIV_DIVSXT;
static const long ID_STATICTEXT17;
static const long ID_RDIV_DIGSXT;
static const long ID_STATICTEXT18;
static const long ID_RDIV_DIVGN;
static const long ID_STATICTEXT19;
static const long ID_RDIV_DIGGN;
static const long ID_STATICTEXT20;
static const long ID_RDIV_DIGSXR;
static const long ID_STATICTEXT21;
static const long ID_RDIV_CPSXT;
static const long ID_STATICTEXT22;
static const long ID_RDIV_DIG;
static const long ID_STATICTEXT23;
static const long ID_RDIV_CPGN;
static const long ID_STATICTEXT24;
static const long ID_RDIV_CPSXR;
static const long ID_STATICTEXT25;
static const long ID_RDIV_SPIBUF;
static const long ID_STATICTEXT26;
static const long ID_RDIV_AFE;
static const long ID_STATICTEXT27;
static const long ID_RDIV_DIGIp2;
static const long ID_STATICTEXT28;
static const long ID_RDIV_DIGIp1;
static const long ID_PANEL2;
static const long ID_NOTEBOOK1;
//*)

private:
//(*Handlers(pnlLDO)
    void ParameterChangeHandler(wxCommandEvent& event);
//*)

protected:
    void BuildContent(wxWindow* parent,wxWindowID id,const wxPoint& pos,const wxSize& size);
    void AssignEnumsToIds();
    DECLARE_EVENT_TABLE()
};
#endif
